import React from "react";
import Header from "./Header";
import { type FC } from "~/utils/types";
import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

export default function Layout({ children }: FC) {
  const { data: session } = useSession();
  const router = useRouter();
  return (
    <div className="flex min-h-screen flex-col font-custom text-base text-gray-600">
      <Head>
        <title>Oh my dog!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="absolute -top-16 -z-10 h-[100vh] w-full overflow-hidden rounded-b-[15%] bg-primary-200">
        {!session && router.pathname === "/" && (
          <div
            className="absolute -bottom-10 right-0"
            style={{
              width: "35vw",
              height: "30vw",
            }}
          >
            <Image
              src="/hero.png"
              fill={true}
              alt="hero"
              className="object-contain"
              style={{
                transform: "scaleX(-1)",
              }}
            />
          </div>
        )}
      </div>
      <main className="z-10 px-20 pt-8 pb-16">{children}</main>
    </div>
  );
}
