import React from "react";
import Header from "./Header";
import { FC } from "~/utils/types";
import Head from "next/head";

export default function Layout({ children }: FC) {
  return (
    <div className="flex min-h-screen flex-col font-custom text-base text-gray-600">
      <Head>
        <title>Oh my dog!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="absolute -top-16 -z-10 h-screen w-full rounded-b-[25%] bg-primary-200"></div>
      <main className="z-10 px-20 py-16">{children}</main>
    </div>
  );
}
