import React from "react";
import Header from "./Header";
import { type FC } from "~/utils/language/types";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

export default function Layout({ children }: FC) {
  const { data: session } = useSession();
  const router = useRouter();
  return (
    <div className="flex min-h-screen flex-col font-custom text-base text-gray-600">
      <Head>
        <title>Oh my dog!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {(router.pathname !== "/" || session) && (
        <div className="absolute -top-16 -z-10 h-[100vh] w-full overflow-hidden rounded-b-[15%] bg-primary-200"></div>
      )}
      <main className="z-10 px-8 py-4 md:px-20 md:pt-8 md:pb-16">
        {children}
      </main>
    </div>
  );
}
